<?php

namespace ExtAss\exampdbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * moviesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class moviesRepository extends EntityRepository
{
public function show()
{
 	$em = $this->getEntityManager();
 	$query = $em->createQuery("SELECT m FROM ExtAssexampdbBundle:movies m")->getArrayResult();
	return $query;
}
public function delete($id)
{
	$em = $this->getEntityManager();
	$result =$em->createQuery("DELETE FROM  ExtAssexampdbBundle:movies m where m.id=$id")->getResult();
	return $result;
}
public function update($id,$title,$director,$released,$genre,$tagline)
{
     $em = $this->getEntityManager();
		$result=$em->createQuery("UPDATE ExtAssexampdbBundle:movies m set m.title='".$title."',m.director='".$director."' ,m.released='".$released."',m.genre='$genre',m.tagline='".$tagline."' WHERE m.id=$id")->getResult();
        return $result; 
}
}
